CSS and Final fies (hopefully)
unh-webappdev/FlashCourses_web pull request #13
Opened 2018-04-26 17:20 UTC by scolarofterra

## Requirements

* This template is required when creating a pull request. If a pull request does not include enough information to be reviewed in a timely manner, it may be closed at the maintainers' discretion.
* All new code requires testing to ensure against regression and conflict with existing code
* Include screenshots when appropriate

### Description of the Change
[Explain]
Addad CSS made final changes to html made page name scheme lineup on all pages.
### Alternate Designs
[if applicable]

### Why Should This Be In FlashCourses?
[Explain]
Makes wanted font settings as what people wanted and makes final fixes
 ### Benefits
[Explain]
Final fixs to code and adds CSS
### Possible Drawbacks
[Explain]
None that i can think of
### Verification Process
[Explain how it was tested]
local testing
### Applicable Issues
[if applicable]

2018-04-28 15:05 UTC, unh-webappdev requested changes
Please add requested 'header' information (e.g., Author, Date Created/Updated, Relative File Path, Description) to each code file. See the sample files located on the repo.

2018-04-28 15:05 UTC, unh-webappdev commented on static/Base.html
> +{% load static %}
Please add requested 'header' information (e.g., Author, Date Created/Updated, Relative File Path, Description) to each code file. See the sample files located on the repo.

2018-04-30 00:47 UTC, scolarofterra commented on static/Base.html
> +{% load static %}
added to all files in this pull will hit the rest in another pull request

2018-04-30 21:58 UTC, unh-webappdev requested changes

2018-04-30 21:58 UTC, unh-webappdev commented on static/Base.html
> +{% load static %}
Sorry, Travis, but I'm going to need you to go in real quickly and fix your HTML tags since they're coming up marked as syntactically incorrect on GitHub.

<!-- Correct HTML comment tags. -->

2018-05-01 01:32 UTC, scolarofterra commented on static/Base.html
> +{% load static %}
should be fixed seems it had a django remnant left that i had missed

2018-05-01 10:05 UTC, merged